spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  devtools:
    livereload:
      enabled: true     # Spring devtools = ??????? ??? ??? ?? ??? ???? ??? ?????, ? ?????? ??? ???? ??
  servlet:
    multipart:                  #?? ???? ??? ??? ????
      max-file-size: 100MB       #???? ?? ??????? ????,
      max-request-size: 100MB    #???? request ??? ??,
  main:
    allow-circular-references: true
  thymeleaf:                    #???? ??,
    enabled: true               # ????? ??? ??? ??,
    prefix: classpath:templates/  # ????? ???? ??
    suffix: .html               # ????? ???? ??? ?? ???
    cache: false                # false? ???? ? ????? ???? ??? ???? ?? ?? ?? ????? ??? ??.??? false?? true,
    encoding: UTF-8             # ???? ??? ??
    mode: HTML                  # ????? HTML ???? HTML5,,
    check-template: true        # ??? ?? template ?? ?? ??
    check-template-location: true # template ?? ?? ?? ??
  datasource:       # HikariCP? ?????? ??, (DB??? ?? ????) ???? = DB? ??? ???? ?? ????? ?????, ?????? ???? ???? ???? ??,
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/practice?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
      username: postgres # postgresql ID
      password: 1111 # ?? postgresql ???? ??
server:
  port: 8092 